name: Send POST Requests to Cloudflared

on:
  workflow_dispatch:
    inputs:
      cloudflared_url:
        required: true
        type: string
        default: 'https://deleted-perth-offline-caroline.trycloudflare.com'

jobs:
  send-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Send POST request
        run: |
          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Bot" \
            -d '{
              "redis_username": "${{ secrets.REDIS_USERNAME }}",
              "redis_password": "${{ secrets.REDIS_PASSWORD }}"
            }' \
            "${{ github.event.inputs.cloudflared_url }}")
          
          echo "Response received:"
          echo "$response"
